language: php
dist: trusty
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.1
    - php: 7.2

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv 5.6)/etc/conf.d/travis.ini

install:
  - travis_retry composer install --no-interaction

script:
  - composer run test
  - composer run check
