language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer install

script:
  - composer run test
  - composer run check
